### ISSUE TITLE
老哥能不能加个实感骑的

### ISSUE THREAD

**Issue by xinchui** [onekb/FucKeePicycle#1]

**Comment by onekb** [comment]
实感骑画质太差了，不爱用。之前也发现过这个问题，接口好像是没返回视频地址，不太确定，感兴趣可以抓包看看。

**Comment by xinchui** [comment]
> 实感骑画质太差了，不爱用。之前也发现过这个问题，接口好像是没返回视频地址，不太确定，感兴趣可以抓包看看。

试了下，也是没有视频，倒计时结束就直接崩了😂
